//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "accounts"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub provider_account_id: Option<String>,
    pub name: String,
    pub account_type: String,
    pub balance_current: Option<Decimal>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub user_id: Option<Uuid>,
    pub mask: Option<String>,
    pub subtype: Option<String>,
    pub official_name: Option<String>,
    pub provider_connection_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    ProviderAccountId,
    Name,
    AccountType,
    BalanceCurrent,
    CreatedAt,
    UpdatedAt,
    UserId,
    Mask,
    Subtype,
    OfficialName,
    ProviderConnectionId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ProviderConnections,
    Transactions,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::ProviderAccountId => ColumnType::String(StringLen::None).def().null().unique(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::AccountType => ColumnType::String(StringLen::None).def(),
            Self::BalanceCurrent => ColumnType::Decimal(Some((12u32, 2u32))).def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::UserId => ColumnType::Uuid.def().null(),
            Self::Mask => ColumnType::String(StringLen::N(4u32)).def().null(),
            Self::Subtype => ColumnType::String(StringLen::None).def().null(),
            Self::OfficialName => ColumnType::String(StringLen::None).def().null(),
            Self::ProviderConnectionId => ColumnType::Uuid.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ProviderConnections => Entity::belongs_to(super::provider_connections::Entity)
                .from(Column::ProviderConnectionId)
                .to(super::provider_connections::Column::Id)
                .into(),
            Self::Transactions => Entity::has_many(super::transactions::Entity).into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::provider_connections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProviderConnections.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
