//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "provider_connections"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub item_id: String,
    pub is_connected: bool,
    pub last_sync_at: Option<DateTimeWithTimeZone>,
    pub connected_at: Option<DateTimeWithTimeZone>,
    pub disconnected_at: Option<DateTimeWithTimeZone>,
    pub institution_name: Option<String>,
    pub transaction_count: Option<i32>,
    pub account_count: Option<i32>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub user_id: Option<Uuid>,
    pub institution_logo_url: Option<String>,
    pub sync_cursor: Option<String>,
    pub institution_id: Option<String>,
    pub provider: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    ItemId,
    IsConnected,
    LastSyncAt,
    ConnectedAt,
    DisconnectedAt,
    InstitutionName,
    TransactionCount,
    AccountCount,
    CreatedAt,
    UpdatedAt,
    UserId,
    InstitutionLogoUrl,
    SyncCursor,
    InstitutionId,
    Provider,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Accounts,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::ItemId => ColumnType::String(StringLen::None).def().unique(),
            Self::IsConnected => ColumnType::Boolean.def(),
            Self::LastSyncAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::ConnectedAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::DisconnectedAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::InstitutionName => ColumnType::String(StringLen::None).def().null(),
            Self::TransactionCount => ColumnType::Integer.def().null(),
            Self::AccountCount => ColumnType::Integer.def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::UserId => ColumnType::Uuid.def().null(),
            Self::InstitutionLogoUrl => ColumnType::String(StringLen::None).def().null(),
            Self::SyncCursor => ColumnType::String(StringLen::None).def().null(),
            Self::InstitutionId => ColumnType::String(StringLen::None).def().null(),
            Self::Provider => ColumnType::String(StringLen::N(50u32)).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Accounts => Entity::has_many(super::accounts::Entity).into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
