//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use sea_orm::Condition;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "transactions"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub account_id: Option<Uuid>,
    pub provider_transaction_id: Option<String>,
    pub amount: Decimal,
    pub date: Date,
    pub merchant_name: Option<String>,
    pub category_primary: String,
    pub category_detailed: String,
    pub category_confidence: String,
    pub payment_channel: Option<String>,
    pub pending: Option<bool>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub user_id: Option<Uuid>,
    pub normalized_merchant: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    AccountId,
    ProviderTransactionId,
    Amount,
    Date,
    MerchantName,
    CategoryPrimary,
    CategoryDetailed,
    CategoryConfidence,
    PaymentChannel,
    Pending,
    CreatedAt,
    UserId,
    NormalizedMerchant,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Accounts,
    TransactionCategoryOverrides,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::AccountId => ColumnType::Uuid.def().null(),
            Self::ProviderTransactionId => ColumnType::String(StringLen::None).def().null(),
            Self::Amount => ColumnType::Decimal(Some((12u32, 2u32))).def(),
            Self::Date => ColumnType::Date.def(),
            Self::MerchantName => ColumnType::String(StringLen::None).def().null(),
            Self::CategoryPrimary => ColumnType::String(StringLen::None).def(),
            Self::CategoryDetailed => ColumnType::String(StringLen::None).def(),
            Self::CategoryConfidence => ColumnType::String(StringLen::None).def(),
            Self::PaymentChannel => ColumnType::String(StringLen::None).def().null(),
            Self::Pending => ColumnType::Boolean.def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::UserId => ColumnType::Uuid.def().null(),
            Self::NormalizedMerchant => ColumnType::Text.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Accounts => Entity::belongs_to(super::accounts::Entity)
                .from(Column::AccountId)
                .to(super::accounts::Column::Id)
                .into(),
            Self::TransactionCategoryOverrides => {
                Entity::belongs_to(super::transaction_category_overrides::Entity)
                    .from(Column::UserId)
                    .to(super::transaction_category_overrides::Column::UserId)
                    .on_condition(|left, right| {
                        Condition::all()
                            .add(Expr::col((left.clone(), Column::UserId)).equals((
                                right.clone(),
                                super::transaction_category_overrides::Column::UserId,
                            )))
                            .add(Expr::col((left, Column::NormalizedMerchant)).equals((
                                right,
                                super::transaction_category_overrides::Column::NormalizedMerchant,
                            )))
                    })
                    .into()
            }
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::transaction_category_overrides::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionCategoryOverrides.def()
    }
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
