//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "users"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub email: String,
    pub password_hash: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub onboarding_completed: bool,
    pub provider: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Email,
    PasswordHash,
    CreatedAt,
    UpdatedAt,
    OnboardingCompleted,
    Provider,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Accounts,
    Budgets,
    ProviderConnections,
    ProviderCredentials,
    SimplefinHiddenOrgs,
    SimplefinRootCredentials,
    TransactionCategoryOverrides,
    Transactions,
    UserCustomCategories,
    WebauthnCredentials,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::Email => ColumnType::String(StringLen::None).def().unique(),
            Self::PasswordHash => ColumnType::String(StringLen::None).def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::OnboardingCompleted => ColumnType::Boolean.def(),
            Self::Provider => ColumnType::String(StringLen::N(20u32)).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Accounts => Entity::has_many(super::accounts::Entity).into(),
            Self::Budgets => Entity::has_many(super::budgets::Entity).into(),
            Self::ProviderConnections => {
                Entity::has_many(super::provider_connections::Entity).into()
            }
            Self::ProviderCredentials => {
                Entity::has_many(super::provider_credentials::Entity).into()
            }
            Self::SimplefinHiddenOrgs => {
                Entity::has_many(super::simplefin_hidden_orgs::Entity).into()
            }
            Self::SimplefinRootCredentials => {
                Entity::has_one(super::simplefin_root_credentials::Entity).into()
            }
            Self::TransactionCategoryOverrides => {
                Entity::has_many(super::transaction_category_overrides::Entity).into()
            }
            Self::Transactions => Entity::has_many(super::transactions::Entity).into(),
            Self::UserCustomCategories => {
                Entity::has_many(super::user_custom_categories::Entity).into()
            }
            Self::WebauthnCredentials => {
                Entity::has_many(super::webauthn_credentials::Entity).into()
            }
        }
    }
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl Related<super::budgets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Budgets.def()
    }
}

impl Related<super::provider_connections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProviderConnections.def()
    }
}

impl Related<super::provider_credentials::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProviderCredentials.def()
    }
}

impl Related<super::simplefin_hidden_orgs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SimplefinHiddenOrgs.def()
    }
}

impl Related<super::simplefin_root_credentials::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SimplefinRootCredentials.def()
    }
}

impl Related<super::transaction_category_overrides::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransactionCategoryOverrides.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::user_custom_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserCustomCategories.def()
    }
}

impl Related<super::webauthn_credentials::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebauthnCredentials.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
